### ISSUE TITLE
Missing package to build

### ISSUE THREAD

**Issue by yt6983138** [microsoft/vs-pty.net#35]
Hello i just decided to fork this project and try to fix segfault on linux (also trying to debug), but i came across this error:
`Unable to find package MicroBuild.VisualStudio. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org`
I can't find this package anywhere, no results on google, in nuget there's a package named `Microsoft.VisualStudioEng.MicroBuild.Core`, but that does not fix the problem, i also looked into the nuget feed a dev mentioned in earlier issue, can't find it either.

**Comment by javierdlg** [comment]
Thanks for reporting this issue, we're quite resource constraint atm so it took a while to get to this. Regardless, I've tested this locally and validated that #36 fixes the issue

Hopefully this won't dissuade you from using this library.
